name: Bug report
description: Report a bug/error
title: "[Bug]: "
labels: ["bug"]
assignees:
  - GleammerRay
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a new bug report!
        
        If you have not found similar open/pinned issues at https://github.com/GlitterWare/Passy/issues then fully describe the problem and provide an error log if available. 
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What went wrong? Please provide a full description of the problem. You may provide image attachments.
  - type: textarea
    id: expected
    attributes:
      label: Expected outcome
      description: What did you expect to happen?
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What were you trying to do when this happened?
  - type: textarea
    id: error-log
    attributes:
      label: Error log
      description: If available, paste the error log here.
  - type: dropdown
    id: app-version
    attributes:
      label: App version
      description: Select the app version. You can find it in the app settings under the `About` section.
      options:
        - v1.6.0 - Markdown Notes
        - v1.5.2 - Windows Hotfix
        - v1.5.1 - The Little Things
        - v1.5.0 - Browser Extension
        - v1.4.1 - Quality Patch
        - v1.4.0 - Sharing is Caring
        - v1.3.1 - Windows Hotfix
        - v1.3.0 - Bulletproof
        - v1.2.0 - Automatic Backups
        - v1.1.1 - Privacy Update
        - v1.0.2 - Better Networking
        - v1.0.1 - History Hotfix
        - v1.0.0 - We're Open!
        - v0.11.1 and lower
  - type: checkboxes
    id: submission-checklist
    attributes:
      label: Submission checklist
      description: Please make sure that this issue meets the submission requirements.
      options:
        - label: I have specified the problem in the issue title
          required: true
        - label: I have provided a verbose description of the problem
          required: true

