name: passy
base: core24
version: 'v1.10.0'
summary: Offline password manager with cross-platform synchronization # 79 char long summary
description: |
  Store passwords, payment cards notes, ID cards and identities offline and safe, synchronized between all of your devices.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

# Improves startup time
compression: lzo

slots:
  dbus-glitterware-passy:
    interface: dbus
    bus: session
    name: org.glitterware.passy

plugs:
  platform-snap:
    interface: content
    target: $SNAP/gnome-platform
  native-messaging-hosts:
    interface: personal-files
    write:
    - $HOME/.mozilla/native-messaging-hosts
    - $HOME/.config/microsoft-edge/NativeMessagingHosts
    - $HOME/.config/google-chrome/NativeMessagingHosts
    - $HOME/.config/chromium/NativeMessagingHosts
    - $HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts
  audio-playback:
    interface: audio-playback

apps:
  passy:
    command: passy
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - platform-snap
      - network
      - home
      - removable-media
      - native-messaging-hosts
      - audio-playback
    slots:
      - dbus-glitterware-passy

parts:
  glitterware-passy:
    source: .
    plugin: dump
    build-packages:
      #region Flutter dependencies
      - curl
      - file
      - git
      - unzip
      - xz-utils
      - zip
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      #endregion

      #region CMake dependencies
      - autoconf
      - automake
      - libtool
      - perl
      #endregion

      #region Passy dependencies
      - libayatana-appindicator3-dev
      - libmpv-dev
      - meson
      #endregion
    stage-packages:
      - zenity
      - libappindicator3-1
      - libmpv2
    override-build: |
      export PATH="/usr/bin:$PATH"
      craftctl default
      export PATH="$PATH:$PWD/submodules/flutter/bin"
      flutter build linux --no-version-check --suppress-analytics --dart-define=UPDATES_POPUP_ENABLED=false
      bash -c "shopt -s extglob dotglob;mkdir foobar;mv $SNAPCRAFT_PART_INSTALL/* foobar;mv foobar/etc $SNAPCRAFT_PART_INSTALL;mv foobar/usr $SNAPCRAFT_PART_INSTALL;mv foobar/var $SNAPCRAFT_PART_INSTALL;rm -rf foobar;mv ./build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL"
      libdir=$(echo "$SNAPCRAFT_PART_INSTALL"/usr/lib/*-linux-gnu)
      ln -sf libmpv.so.2.2.0 "$libdir/libmpv.so.2"
      ln -sf libmpv.so.2.2.0 "$libdir/libmpv.so"
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
