name: passy
base: core22
version: 'v1.9.3'
summary: Offline password manager with cross-platform synchronization # 79 char long summary
description: |
  Store passwords, payment cards notes, ID cards and identities offline and safe, synchronized between all of your devices.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

# Improves startup time
compression: lzo

slots:
  dbus-glitterware-passy:
    interface: dbus
    bus: session
    name: org.glitterware.passy

plugs:
  platform-snap:
    interface: content
    target: $SNAP/gnome-platform
  native-messaging-hosts:
    interface: personal-files
    write:
    - $HOME/.mozilla/native-messaging-hosts
    - $HOME/.config/microsoft-edge/NativeMessagingHosts
    - $HOME/.config/google-chrome/NativeMessagingHosts
    - $HOME/.config/chromium/NativeMessagingHosts
    - $HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts
  audio-playback:
    interface: audio-playback

apps:
  passy:
    command: passy
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - platform-snap
      - network
      - home
      - removable-media
      - native-messaging-hosts
      - audio-playback
    slots:
      - dbus-glitterware-passy

parts:
  glitterware-passy:
    source: https://github.com/GlitterWare/Passy.git
    source-branch: dev
    plugin: dump
    build-packages:
      #region Flutter dependencies
      - curl
      - file
      - git
      - unzip
      - xz-utils
      - zip
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      #endregion

      #region Passy dependencies
      - libayatana-appindicator3-dev
      - libmpv-dev
      - mpv
      #endregion
    stage-packages:
      - zenity
      - libappindicator3-1
      - libmpv1
    override-build: |
      craftctl default
      export PATH="$PATH:$PWD/submodules/flutter/bin"
      ./submodules/flutter/bin/flutter --no-version-check --suppress-analytics build linux --dart-define=UPDATES_POPUP_ENABLED=false
      export PASSY_BUNDLE_PATH="./build/linux/x64/release/bundle"
      if [ ! -d "$PASSY_BUNDLE_PATH" ]; then
        export PASSY_BUNDLE_PATH="./build/linux/arm64/release/bundle"
      fi
      bash -c "shopt -s extglob dotglob;mkdir foobar;mv $SNAPCRAFT_PART_INSTALL/* foobar;mv foobar/etc $SNAPCRAFT_PART_INSTALL;mv foobar/usr $SNAPCRAFT_PART_INSTALL;mv foobar/var $SNAPCRAFT_PART_INSTALL;rm -rf foobar;mv $PASSY_BUNDLE_PATH/* $SNAPCRAFT_PART_INSTALL"
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
