name: Build Passy for Windows
on:
  workflow_dispatch:
jobs:
  build_windows:
    name: Build Passy for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install flutter
        shell: bash
        run: |
          git submodule init
          git submodule update
          echo "$PWD/submodules/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/submodules/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
      - name: Configure flutter
        shell: bash
        run: flutter config --no-analytics
      - name: Build Passy for Windows
        shell: bash
        run: flutter --no-version-check --suppress-analytics build windows
      - name: Prepare releases
        shell: bash
        run: |
          cd ..
          mkdir -p build/windows-portable/Passy
          cp -r Passy/build/windows/runner/Release/. build/windows-portable/Passy
      - name: Upload Windows portable build
        uses: actions/upload-artifact@v3
        with:
          name: windows-portable
          path: D:\a\Passy\build\windows-portable
