name: Build Passy for Linux ARM64
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, review_requested ]
    branches:
      - main
      - dev
jobs:
  build_linux_arm64:
    name: Build Passy for Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Create build directory
        shell: bash
        run: |
          cd ..
          mkdir build
          mkdir bin
          cd bin
          wget https://raw.githubusercontent.com/GlitterWare/Passy/$GITHUB_SHA/.github/workflows/arm64.sh
          chmod +x arm64.sh
      - name: Install dependencies
        shell: bash
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static qemu-system-arm
      - name: Build for ARM64
        uses: tj-actions/docker-run@v2
        with:
          image: ubuntu:20.04
          name: ubuntu
          options: --rm --platform linux/arm64 -v $PWD:/Passy -v /home/runner/work/Passy/build:/passy-build -v /home/runner/work/Passy/bin:/passy-bin
          args: /passy-bin/arm64.sh
      - name: Archive Passy CLI build
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          directory: ../build
          filename: Passy-CLI-Linux-ARM64.zip
          path: cli
      - name: Archive Passy build
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          directory: ../build
          filename: Passy-Linux-ARM64.zip
          path: Passy
      - name: Upload Passy CLI build
        uses: actions/upload-artifact@v4
        with:
          name: passy-cli-linux-arm64
          path: /home/runner/work/Passy/build/Passy-CLI-Linux-ARM64.zip
      - name: Upload Passy build
        uses: actions/upload-artifact@v4
        with:
          name: passy-linux-arm64
          path: /home/runner/work/Passy/build/Passy-Linux-ARM64.zip
